[package]
name = "nisqa-core"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[lib]
crate-type = ["staticlib"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-nostartfiles", "-C", "link-arg=-nostdlib"]
